# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alternatives numériques
email: alxnbl@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: alxnbl.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://alxnbl.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /digital-alternatives      # place folder name if the site is served in a subfolder
twitter_username: ""
github_username:  alxnbl

# Build settings
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect
#remote_theme: THEME-NAME

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
language_default: fr

#collections_dir: content
collections:
  fr:
    output: true
    permalink: /:collection/:slug
    #sort_by: custom_field
    # order:
    #   - a.md
    #   - b.md
    #permalink: /:collection/:name
  en:
    output: true
    permalink: /:collection/:slug

defaults:
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'news/:title'
    language: en
- scope:
    path: '_posts/nl'
    type: 'posts'
  values:
    permalink: 'nieuws/:title'
    language: nl


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "fr"
    values:
      layout: "page"
  -
    scope:
      path: "_fr/posts"
    values:
      layout: "post"
      permalink: /fr/post/:slug
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "page"
  -
    scope:
      path: "_en/posts"
    values:
      layout: "post"
      permalink: /en/post/:slug


      