# Site settings
title: 'Alternatives numériques'
description: 'TBC'

domain: alxnbl.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://alxnbl.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: '/digital-alternatives' # the subpath of your site, e.g. /blog
absoluteurl: 'https://alxnbl.github.io/digital-alternatives'

#version: '2021-01-01'

default_language: 'fr'
fallback_page: 'stories'

timezone: Europe/Paris
encoding: utf-8

# Build settings
#markdown: kramdown

# Markdown Processors
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 2..3


remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links


# Defaults
defaults:
-
  scope:
    path: 'en'
    type: 'page'
  values:
    page-type: page
-
  scope:
    path: 'fr'
    type: 'page'
  values:
    page-type: page
-
  scope:
    path: 'en/alternatives'
    type: 'page'
  values:
    layout: page_l2
    depthLevel: 2
    category: alternatives
-
  scope:
    path: 'fr/alternatives'
    type: 'page'
  values:
    layout: page_l2
    depthLevel: 2
    category: alternatives
-
  scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/stories/:title'
    language: en
-
  scope:
    path: '_posts/fr'
    type: 'posts'
  values:
    permalink: 'fr/stories/:title'
    language: fr
